### ISSUE TITLE
v0.4 summary issue

### ISSUE THREAD

**Issue by rtimms** [FaradayInstitution/BPX#42]
Roadmap issues:

- [x] blended electrodes https://github.com/pybamm-team/BPX/issues/23
- [x] validation based on models https://github.com/pybamm-team/BPX/issues/29
- [x] "additional" parameters https://github.com/pybamm-team/BPX/issues/26
- [ ] ~~split validity from completeness https://github.com/pybamm-team/BPX/issues/40~~
- [x] extra examples to show off hysteresis (via additional parameters) and blended electrodes 
- [x] API docs
- [x] user guide
- [x] change **a_n** and **a_p** to **b_n** and **b_p** (the surface area per unit volume) in eq. (6c) in the BPX document -- a small bug fix

Extras:

- [ ] active material volume specification https://github.com/pybamm-team/BPX/issues/41
